"""Adds year discovered to moon model

Revision ID: 075b82457917
Revises: 2e096285f6f9
Create Date: 2025-11-04 14:34:47.613824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '075b82457917'
down_revision = '2e096285f6f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('year_discovered', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moon', schema=None) as batch_op:
        batch_op.drop_column('year_discovered')

    # ### end Alembic commands ###
